### ISSUE TITLE
to_xml or to_json support

### ISSUE THREAD

**Issue by rx** [spikex/strongbox#11]
WIth binary columns both some_encrypted_model_instance.to_xml and some_encrypted_model_instance.to_json do not work.  I expected them to return *\* encrypted *\* values.

**Comment by MatTarantini** [comment]
I'm receiving `SystemStackError: stack level too deep` errors when trying to use to_json. Same situation that rx had described. Binary column. Encrypted model instance. On version 0.7.2.

Adding as_json resolves it. @spikex I thought you had pushed up the fix? Or did the fix not involve as_json?
